apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose.exe convert -v
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: notificationservice
  name: notificationservice
spec:
  containers:
    - env:
        - name: spring_rabbitmq_host
          value: rabbitmqeightshop
      image: thocorr/fiapfase4_notificationservice:latest
      name: notificationservice
      ports:
        - containerPort: 7088
      resources: {}
  restartPolicy: OnFailure
status: {}
