apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose.exe convert -v
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: notificationservice
  name: notificationservice
spec:
  ports:
    - name: "7088"
      port: 7088
      targetPort: 7088
  selector:
    io.kompose.service: notificationservice
status:
  loadBalancer: {}
