apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose.exe convert -v
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmqeightshop
  name: rabbitmqeightshop
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "5673"
      port: 5673
      targetPort: 5673
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    io.kompose.service: rabbitmqeightshop
status:
  loadBalancer: {}
